# ===========================================
# Site Settings
# ===========================================
# Header
site_title: adiynil
site_description: Web前端开发，中国广州。 to Produce wonderful ideas.
# ---Optional ---
site_avatar: /images/avatar.jpg
artical_license_statement: 本文由adiynil原创编写，转载请尽量保留版权网址，感谢您的理解与分享!
# ---End Optional ---
menu:
  Home: /
  Archives: /archives
  AboutMe: /about
social_link:
  email: aadiynil#gmail.com
# display widgets
widgets:
# - social_links
- search
- recent_posts
- archives
- tagcloud

# widget behavior
archive_type: 'monthly'
show_count: true
# Content
excerpt_link: Read More
# favico 
favicon:

# ===========================================
# Miscellaneous Settings
# ===========================================
# Baidu Analytics
baidu_analytics:
# Google Analytics
google_analytics:
addthis_analytics:
# Disqus
disqus:
  enable: true
  shortname: adiynil
  count: true
# changyan
changyan:
  enable: false
  appid:
  appkey:
# duoshuo
duoshuo:
  enable: false
  shortname:
# Visitors
leancloud_visitors:
  enable: false
  app_id:
  app_key:
donation:
  enable: false
  alipay:
  wechat:

# Search 
# Note: please install hexo-generator-search plugin and config the root _config.yml (not theme's _config.yml) as below value search.json(https://www.npmjs.com/package/hexo-generator-search):
# search:
#   path: search.xml
#   field: post
