name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: public
        BUILD_SCRIPT: npm install hexo -g && npm install && hexo clean && hexo g